project:
  type: manuscript
  output-dir: docs

manuscript:
  article: docs/index.qmd

format:
  html:
    df-print: kable
  pdf: default
  # docx: default
  jats: default

execute:
  freeze: true



